

let metalExample ={
  states:{

  },
  pipeline:{
    elements:{
      source_1:{
        position:{
          x:0,
          y:0
        },
        type:'source',
        url:'music/bass.mp3',
      },
      source_2:{
        position:{
          x:0,
          y:0
        },
        type:'source',
        url:'music/drums.mp3',
      },
      source_3:{
        position:{
          x:0,
          y:0
        },
        type:'source',
        url:'music/guitar.mp3',
      },
      source_4:{
        position:{
          x:0,
          y:0
        },
        type:'source',
        url:'music/rhytm_guitar.mp3',
      },
      gain_1:{
        position:{
          x:0,
          y:0
        },
        type:'gain'
      },
      gain_2:{
        position:{
          x:0,
          y:0
        },
        type:'gain'
      },
      gain_3:{
        position:{
          x:0,
          y:0
        },
        type:'gain'
      },
      gain_4:{
        position:{
          x:0,
          y:0
        },
        type:'gain'
      },
      output_1:{
        position:{
          x:0,
          y:0
        },
        type:'output',
      },

    },
    connections:{
      stream:[
        {
          from:{id:'source_1',out:'default'},
          to:{id:'gain_1',in:'default'}
        },
        {
          from:{id:'source_2',out:'default'},
          to:{id:'gain_2',in:'default'}
        },
        {
          from:{id:'source_3',out:'default'},
          to:{id:'gain_3',in:'default'}
        },
        {
          from:{id:'source_4',out:'default'},
          to:{id:'gain_4',in:'default'}
        },
        {
          from:{id:'gain_1',out:'default'},
          to:{id:'output_1',in:'default'}
        },
        {
          from:{id:'gain_2',out:'default'},
          to:{id:'output_1',in:'default'}
        },
        {
          from:{id:'gain_3',out:'default'},
          to:{id:'output_1',in:'default'}
        },
        {
          from:{id:'gain_4',out:'default'},
          to:{id:'output_1',in:'default'}
        },
      ]
    }
  }
}
export {metalExample}
